### ISSUE TITLE
Update Readme.md to have examples of usage 

### ISSUE THREAD

**Issue by Watercycle** [Jake-NSW/Signals#1]
I saw this on [asset.party](https://asset.party/woosh/signals) and it sounds super useful! If it's not too much trouble, would you be willing to add some examples demonstrating how to use it (e.g. to the README)?

**Comment by korvemaa** [comment]
Hi watercycle :)

I didnt intend on signals being used for general public use (hence the bare readme), had to upload it to asset party so a friend could play my sbox game.

if you would like to know how it works, my game uses it extensively for basically everything [github.com/Jake-NSW/Espionage](https://github.com/Jake-NSW/Espionage).

I will go about adding some more simple examples to the readme if my game source code doesn't surffice :)

**Comment by Watercycle** [comment]
Ooh, perfect! Thank you! Still trying to get my bearings on what the development process is like in s&box.

**Comment by Watercycle** [comment]
Going to close this issue since the s&box API isn't particularly stable - it's a little silly to ask for documentation with that in mind! Nonetheless, thank you for sharing this project! Always love seeing different ways to organize event logic!
